# Знакомство с PyTorch

## Введение

Библиотека PyTorch является универсальным инструментом машинного обучения. Она популярна работе с нейронными сетями. Является open-source проектом. В библиотеке есть четыре ключевых составляющих:

* Развитый инструментарий для работы с тензорами. Он похож на numpy, но даёт дополнительные возможности по контролю выделяемой памяти, что важно при работе с большими моделями и данными.

* Простое построение динамического вычислительного графа, позволяющего получать градиенты целевых функций от параметров модели.

* Большой набор готовых слоёв для построения нейронных сетей произвольной архитектуры.

* Возможность перенаправлять вычисления на графические процессоры GPU.


In [ ]:
import torch
 
e  = torch.eye(3) # единичная матрица 3x3
print(e) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Тензоры

Тензор - это основной объект в *PyTorch*. Тензоры схожи с *ndarrays* в *NumPy*, с добавлением того, что тензоры могут быть использованы на GPU для ускорения вычислений.

* Тензор - это набор из элементов одного типа. 
* Тензоры могут быть одномерные (векторы), двумерные (матрицы), трехмерные и так далее - любой размерности.

In [ ]:
a = torch.rand(5, 3) # сгенерировали матрицу 5x3 из случайных чисел
a

tensor([[0.3089, 0.9618, 0.1672],
        [0.2231, 0.5418, 0.2646],
        [0.0355, 0.6424, 0.1923],
        [0.6987, 0.5001, 0.6931],
        [0.0327, 0.4032, 0.3457]])

In [ ]:
a.shape # посмотрели размеры

torch.Size([5, 3])

In [ ]:
a + 3 # добавили 3 ко всем элементам

tensor([[3.3089, 3.9618, 3.1672],
        [3.2231, 3.5418, 3.2646],
        [3.0355, 3.6424, 3.1923],
        [3.6987, 3.5001, 3.6931],
        [3.0327, 3.4032, 3.3457]])

## Вычисления на видеокарте

Если на компьютере есть графическая карта, то можно осуществлять вычисления на ней - обычно это ускоряет вычисления в разы.

Проведем эксперимент:
1. Сначала создадим две единичных матрицы большой размерности и перемножим их как обычно, используя мощности центрального процессора (CPU), засечем время.

2. Затем создадим такие же тензоры, перенесем их на GPU, там сделаем умножение и вернем результат на CPU (можно сразу создавать тензоры на GPU, но обычно придерживаются первого варианта). Также замерим время и сравним.

**Первый вариант (CPU)**

In [ ]:
%%time

x1 = torch.eye(10000)
y1 = torch.eye(10000)
z1 = x1.mm(y1)   

CPU times: user 24.2 s, sys: 455 ms, total: 24.7 s
Wall time: 24.7 s


**Второй вариант (GPU)**

In [ ]:
cpu = torch.device("cpu")
gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [ ]:
%%time

x1 = torch.eye(10000).to(gpu)
y1 = torch.eye(10000).to(gpu)
z1 = x1.mm(y1).to(cpu)  

CPU times: user 817 ms, sys: 1.52 ms, total: 819 ms
Wall time: 815 ms
